# theme: jekyll-theme-minimal
# title: George's homepage
# description: A website at last!



name: George Igwegbe 
# permalink: /:title/
# baseurl: https://kylieying.com
# baseurl: ""
permalink: /blog/:title

# seo tag
# plugins:
#   - jekyll-seo-tag

# Google Analytics
# google_analytics: G-TEEDE1GB8S
