# theme: jekyll-theme-minimal
# title: George's homepage
# description: A website at last!



name: George Igwegbe 
# permalink: /:title/
# baseurl: https://georgeigwegbe.com
# baseurl: ""
permalink: /blog/:title

collections:
  notes:
    output: true
    permalink: /notes/:title/
  blogs:
    output: true
    permalink: /blogs/:title/
  things:
    output: true
    permalink: /things/:title/

    
# seo tag
# plugins:
#   - jekyll-seo-tag

# Google Analytics
# google_analytics: G-TEEDE1GB8S
